# Generated by Django 5.2 on 2025-05-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lillies_backend', '0002_product_allergens_product_calories_and_more'),
    ]

    operations = [
    ]
